[package]
name = "gdp-web"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
bytes.workspace = true
gdp-core = { path = "../gdp-core" }
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true